# Generated by Django 3.0.4 on 2021-12-01 12:48

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0031_auto_20211201_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=20, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='名前(20文字まで)'),
        ),
    ]
